version: "2"

services:
  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana
    environment:
            - GF_SERVER_ROOT_URL=http://localhost
            - GF_SECURITY_ADMIN_PASSWORD=123456
            - TZ="America/Bahia"
    # Volume:
    #   - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    user: "104"
 postgres_db:
    image: postgres:11
    container_name: "postgres"
    environment:
      - POSTGRES_DB=grafana
      - POSTGRES_USER=grafana
      - POSTGRES_PASSWORD="123456"
      - TZ="America/Bahia"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
